### ISSUE TITLE
Crash while using home, warp

### ISSUE THREAD

**Issue by bradleygill** [ProjectEssentials/ProjectEssentials#10]
### Describe the bug
> - When using /sethome or /setwarp the server crashes

Running minimal mods, wondering if it's just because the latest version of Forge goofed something up or not.  I figured this was the best place to start.

Any help is appreciated,  Google is a very poor friend when searching for solutions to this.

Sincerely,
Brad
###########################################################################

---- Minecraft Crash Report ----
// Don't do that.

Time: 3/4/20, 8:28 PM
Description: Exception in server tick loop

java.lang.IllegalAccessError: class com.mairwunnx.projectessentials.warps.commands.SetWarpCommand tried to access private field net.minecraft.entity.Entity.field_70165_t (com.mairwunnx.projectessentials.warps.commands.SetWarpCommand and net.minecraft.entity.Entity are in unnamed module of loader cpw.mods.modlauncher.TransformingClassLoader @3c6aa04a)
	at com.mairwunnx.projectessentials.warps.commands.SetWarpCommand.execute(SetWarpCommand.kt:56) ~[?:1.14.4-1.2.2] {re:classloading}
	at com.mairwunnx.projectessentials.warps.commands.SetWarpCommand.access$execute(SetWarpCommand.kt:20) ~[?:1.14.4-1.2.2] {re:classloading}
	at com.mairwunnx.projectessentials.warps.commands.SetWarpCommand$register$1$1.run(SetWarpCommand.kt:36) ~[?:1.14.4-1.2.2] {re:classloading}
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[?:?] {re:classloading}
	at net.minecraft.command.Commands.func_197059_a(Commands.java:205) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147361_d(ServerPlayNetHandler.java:990) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147354_a(ServerPlayNetHandler.java:973) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CChatMessagePacket.func_148833_a(SourceFile:9) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:731) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:141) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:714) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:694) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows Server 2019 (amd64) version 10.0
	Java Version: 11.0.3, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 1839198744 bytes (1753 MB) / 2147483648 bytes (2048 MB) up to 3221225472 bytes (3072 MB)
	CPUs: 12
	JVM Flags: 2 total; -Xms2G -Xmx3G
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtime_enum_extender PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-2.0.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.1.18.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.18
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		forge-1.15.2-31.1.18-server.jar Minecraft {minecraft@1.15.2 DONE}
		luckyblock-1.15.2-1.jar Lucky Block {lucky@1.15.2-1 DONE}
		Project+Essentials+Cooldown-1.14.4-1.0.3.jar Project Essentials Cooldown {project_essentials_cooldown@1.14.4-1.0.3 DONE}
		Project+Essentials+Chat-1.14.4-1.1.0.jar Project Essentials Chat {project_essentials_chat@1.14.4-1.1.0 DONE}
		Project+Essentials+Home-1.14.4-1.1.2.jar Project Essentials Home {project_essentials_home@1.14.4-1.1.2 DONE}
		forge-1.15.2-31.1.18-universal.jar Forge {forge@31.1.18 DONE}
		Project+Essentials+Warps-1.14.4-1.2.2.jar Project Essentials Warps {project_essentials_warps@1.14.4-1.2.2 DONE}
		Xaeros_Minimap_20.5.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.5.0 DONE}
		Project+Essentials+Permissions-1.14.4-1.2.0.jar Project Essentials Permissions {project_essentials_permissions@1.14.4-1.2.0 DONE}
		Project+Essentials+Spawn-1.14.4-1.1.2.jar Project Essentials Spawn {project_essentials_spawn@1.14.4-1.1.2 DONE}
		Project+Essentials-1.14.4-1.0.0.jar Project Essentials {project_essentials@1.14.4-1.0.0 DONE}
		ProjectEssentials-Core-MOD-1.14.4-1.2.1.jar Project Essentials Core {project_essentials_core@1.14.4-1.2.1 DONE}
		Project+Essentials+Backup-1.14.4-1.0.1.jar Project Essentials Backup {project_essentials_backup@1.14.4-1.0.1 DONE}
	Player Count: 1 / 20; [ServerPlayerEntity['Lestibournes'/229, l='world', x=-423.62, y=70.00, z=251.07]]
	Data Packs: vanilla, mod:forge (incompatible), mod:lucky (incompatible), mod:xaerominimap, mod:project_essentials (incompatible), mod:project_essentials_backup (incompatible), mod:project_essentials_chat (incompatible), mod:project_essentials_cooldown (incompatible), mod:project_essentials_core (incompatible), mod:project_essentials_home (incompatible), mod:project_essentials_permissions (incompatible), mod:project_essentials_spawn (incompatible), mod:project_essentials_warps (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

**Comment by MairwunNx** [comment]
You are using warps for 1.14.4 when you playing on minecraft 1.15.2.
You need download warps mod for 1.15.2 forge.

**Comment by MairwunNx** [comment]
Please, give feedback if you still getting crash while using waprs / home module and provide me more information.

Also for logs use pastebin or gist.

**Comment by bradleygill** [comment]
I thought something was suspicious with the version numbers, but I dug around and those were the only ones available for download on Curse.  So I figured it was just me being over critical.  I will try to find the downloads for the 1.15 versions again unless you happen to have a direct link if they are buried somewhere in the git.  Thank you for your prompt reply!   Sorry about the text splat. I completely forgot about pastebin.  I was trying to find a way for a spoiler or code bin type of thing. But yeah.  I don’t usually bother you guys but it really had me stumped last night.  Thanks!

Brad

**Comment by bradleygill** [comment]
I dug around in the git, and I completely missed the little menu option toward the top left that selects the version of minecraft.  I have downloaded all the correct versions and everything seems to be working fine!  Thank you so much for making this mod!  Appreciate the help.
